# @package _group_
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 250]
    num_zombie_walkers: [0, 1]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 1]
    num_zombie_walkers: [0, 1]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 300]
    num_zombie_walkers: [0, 1]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 250]
    num_zombie_walkers: [0, 1]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 200]
    num_zombie_walkers: [0, 1]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [0, 160]
    num_zombie_walkers: [0, 1]
    weather_group: dynamic_1.0
  gpu: [0]